#! /usr/bin/bash
echo "0: to exit"
i=1
while read p; do
  echo "$i: $p"
  let i++
done < /home/ziesmow/.cache/YTools/subs/sub.name
echo -n "jaki film obejrzeć ?: "
read filmid 
if [[ $filmid == 0 ]]; then
  exit
fi
kanal=$(sed -n "${filmid}p" /home/ziesmow/.cache/YTools/subs/sub.links)

video=$(yt-dlp --flat-playlist --print "%(title)s" "https://www.youtube.com/@$kanal/videos" --playlist-end 1)
id=$(yt-dlp --flat-playlist --print "https://youtu.be/%(id)s" "https://www.youtube.com/@$kanal/videos" --playlist-end 1) 

figlet -w 1000 "$video"
thumb $id
read nic
yt $id
