#! /usr/bin/bash
if [[ $1 == "" ]]; then
  echo "brak argumentów koniec z parsowaniem"
  exit 1
fi
echo $1 >> /home/ziesmow/.cache/YTools/ytlinks/youtube.links 
echo ${@:2} >> /home/ziesmow/.cache/YTools/ytlinks/youtube.description
